---
- name: Replace PKCS#12 certificates on ClearPass
  hosts: publishers
  connection: local
  gather_facts: false
  roles:
    - role: clearpass_cert
      vars:
        clearpass_cert_action: replace_p12
